#!/usr/bin/env python

import argparse

#
# surfarea 2:
#   select all receptor atoms within distance of any ligand atom and sum the reported sas/ses values (surface area) per atom type

parser = argparse.ArgumentParser()
parser.add_argument('protein_key', nargs='+')
parser.add_argument('--distance', type=float, default=5.0)

args = parser.parse_args()

import logging
logging.basicConfig(level=logging.INFO)

import os
import sys

import csv
import json
import numpy as np
from scipy.spatial.distance import cdist

from PDB import PDBFile

from collections import Counter

import textwrap
import pickle as pkl

fieldnames = ['protein_key', 'atom_type', 'ses', 'sas']
csvw = csv.DictWriter(sys.stdout, fieldnames, dialect='excel-tab')
csvw.writeheader()

for protein_key in args.protein_key:
    # read distance to ligand (stored in occupancy field)
    fn = f'../{protein_key}.receptor.pdb'
    with open(fn, 'rt', encoding='utf-8') as f:
        pdbf = PDBFile()
        pdbf.parsepdb(f)

    # only heavy atoms
    ligand_dist = np.array([a.occupancy for a in pdbf.struc.atoms if a.element != 'H'])

    # read atom types and coords
    fn = f'{protein_key}.receptor.pdbqt'
    with open(fn, 'rt', encoding='utf-8') as f:
        pdbf = PDBFile()
        pdbf.parsepdb(f)

    # only for heavy atoms
    atomtypes = []
    for r in pdbf.struc.residuebyid:
        # fix certain issues in atom typing here

        for a in r.atoms:
            a.atomtype = a.pdbline[77:79].strip()
            # these are incorrectly generated by openbabel
            if (a.resname == 'DA') and (a.name == 'C8'): a.atomtype = 'A'
            elif (a.resname == 'DA') and (a.name == 'C6'): a.atomtype = 'A'
            elif (a.resname == 'DA') and (a.name == 'N6'): a.atomtype = 'N'
        all_coords = [a.coords for a in r.atoms]
        h_coords = [a.coords for a in r.atoms if a.atomtype == 'HD']
        if h_coords:
            distances = cdist(np.array(all_coords), np.array(h_coords), 'euclidean')
            distances = np.min(distances, axis=1)
        else:
            distances = [999.0] * len(all_coords)
        # N and O atoms with a bound H (nearby H) are (also) H-bond donors
        for i, a in enumerate(r.atoms):
            if distances[i] < 1.4:
                if a.atomtype in ('N', 'NA', 'OA', 'SA', 'S'): logging.debug(f'converting atom {a.name} {a.resname} {a.pdbresid} type from {a.atomtype}')
                if a.atomtype == 'N': a.atomtype = 'ND'
                elif a.atomtype == 'NA': a.atomtype = 'NB'
                elif a.atomtype == 'OA': a.atomtype = 'OB'
                elif a.atomtype == 'SA': a.atomtype = 'SB'
                elif a.atomtype == 'S': a.atomtype = 'SD'
                elif a.atomtype != 'HD': logging.error(f'unexpected atom type for atom {a.name} {a.resname} {a.pdbresid}: "{a.atomtype}"')
                if a.atomtype == 'NB': logging.debug(f'***** atom type {a.atomtype}: {a.name} {a.resname} {a.pdbresid}')
            if a.atomtype != 'HD': atomtypes.append(a.atomtype)

    # indices of heavy atoms within pdbqt file
    heavy_atom_idx = []
    for i, a in enumerate(pdbf.struc.atoms):
        a.index = i
        if a.atomtype != 'HD': heavy_atom_idx.append(i)

    heavy_atoms = [a for a in pdbf.struc.atoms if a.atomtype != 'HD']
    heavy_atom_coords = np.array([a.coords for a in heavy_atoms])

    logging.info('len(ligand_dist)=%s', len(ligand_dist))
    logging.info('len(atomtypes)=%s', len(atomtypes))
    logging.info('len(heavy_atoms)=%s', len(heavy_atoms))
    logging.info('len(heavy_atoms_idx)=%s', len(heavy_atom_idx))

    # read surface info
    ses = dict()
    sas = dict()
    fn = f'{protein_key}.area'
    with open(fn, 'rt', encoding='utf-8') as f:
        # skip first line
        header = next(f)
        for line in f:
            l = line.strip().split()
            # for some reason the area calculation may give nan
            if l[1] != 'nan': ses[int(l[0])] = float(l[1])
            else: ses[int(l[0])] = 0.0
            if l[2] != 'nan': sas[int(l[0])] = float(l[2])
            else: sas[int(l[0])] = 0.0

    logging.info('len(sas)=%s', len(sas))
    logging.info('len(ses)=%s', len(ses))

    idx = np.flatnonzero(ligand_dist < args.distance)

    selected_atoms = []
    cumulative_ses = dict()
    cumulative_sas = dict()
    for i in idx:
        a = heavy_atoms[i]
        selected_atoms.append(i)
        # donor and acceptor atoms can have several
        atom_type = atomtypes[i]
        """
        if atom_type in ('NB', 'OB', 'SB'):
            atom_types = [atom_type.replace('B', 'A'), atom_type.replace('B', 'D')]
        else:
            atom_types = [atom_type]
        """
        atom_types = [atom_type]
        logging.debug('%s atom contribution: %s %s %s %s', protein_key, a.name, a.resname, a.pdbresid, atom_types)
        for atom_type in atom_types:
            cumulative_ses[atom_type] = cumulative_ses.get(atom_type, 0.0) + ses[i]/len(atom_types)
            cumulative_sas[atom_type] = cumulative_sas.get(atom_type, 0.0) + sas[i]/len(atom_types)

    logging.debug('pymol selection: index %s', '+'.join(str(heavy_atom_idx[x]+1) for x in sorted(selected_atoms)))

    for atom_type in sorted(cumulative_ses.keys()):
        csvw.writerow({
            'protein_key': protein_key,
            'atom_type': atom_type,
            'ses': cumulative_ses[atom_type],
            'sas': cumulative_sas[atom_type],
        })
